version: "3.7"

services:
  finance_db:
    container_name: finance_db
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - /etc/finance_db.env
    volumes:
      - /data/finance_data:/var/lib/postgresql/data

  finance:
    image: finance
    container_name: finance
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - finance_db
    ports:
      - "8000:8000"
    volumes:
      - /etc/finance.env:/src/.env
    command:
      ['start.sh']

  rabbitmq:
    image: rabbitmq:latest
    env_file:
      - /etc/finance.env
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /data/finance_rmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /data/finance_redis_data:/data

  finance_worker:
    image: finance
    container_name: finance_worker
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - /etc/finance.env
    restart: always
    command:
      [ 'worker.sh' ]

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - /etc/finance_prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana


volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/finance_prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/finance_grafana_data
