version: "3.7"

services:
  finance_db:
    container_name: finance_db
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - /etc/finance_db.env
    volumes:
      - /data/finance_data:/var/lib/postgresql/data

  finance:
    image: finance
    container_name: finance
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - finance_db
    ports:
      - "8000:8000"
    volumes:
      - /etc/finance.env:/src/.env
      - ./:/src
    command:
      ['./scripts/start.sh']

  rabbitmq:
    image: rabbitmq:latest
    env_file:
      - /etc/finance.env
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /data/finance_rmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /data/finance_redis_data:/data

  finance_worker:
    image: finance
    container_name: finance_worker
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - /etc/finance.env
    restart: always
    command:
      [ './scripts/worker.sh' ]
